In [1]:
import pandas as pd
import pickle as pkl

from datetime import timedelta
from tqdm.notebook import tqdm

In [2]:
with open('data/unmatched_closings3.pkl', 'rb') as f:
    unmatched_listings = pkl.load(f)

In [3]:
len(unmatched_listings)

11905

In [4]:
unmatched_listings.head()

,id,rebny_id,building_id,address,zip,sold_price,last_event,add_address_lid,add_house_number,add_prefix_direction,add_street_name,add_suffix_direction,add_suffix_type,parcel_lid,assessment_lid,land_assessed_value,land_market_value,match_key,normalized_address,check_zip
3,28706220,20111743,NaN,2095 East Post Road,52302,865000,2011-11-18 05:01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2095 EAST POST ROAD,2095 E POST RD,52302
4,28732272,20115298,NaN,LT 253 CEDAR SPRINGS PT 7,52317,109900,2011-11-15 05:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LT 253 CEDAR SPRINGS PT 7,LT 253 CEDAR SPGS PT 7,52317
12,28729393,20093328,NaN,LT 103 CEDAR SPRINGS PART 5,52317,40000,2011-11-22 05:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LT 103 CEDAR SPRINGS PART 5,LT 103 CEDAR SPGS PART 5,52317
18,28732255,20095926,NaN,LT 31 LONGVIEW ESTATES,52317,49900,2011-11-14 05:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LT 31 LONGVIEW ESTATES,LT 31 LONGVIEW ESTS,52317
26,28726935,20115388,15169242.0,403 Washington,52361,85000,2011-12-19 05:00:00,06063L1WT7LH3O2BINYNPA,403,NaN,Washington,NaN,St,020391FUF85CEPFR55AA2X,03041XTK0Q62DD4EL8XU42,16950.0,16950.0,403 WASHINGTON,403 WASHINGTON,52361

In [5]:
with open('data/off_market_sales3.pkl', 'rb') as f:
    oms = pkl.load(f)
len(oms)

369297

In [6]:
oms.head()

,DEED_LID,SITE_ADDR,SITE_CITY,SITE_ZIP,DATE_TRANSFER,VAL_TRANSFER,SITE_HOUSE_NUMBER,SITE_DIRECTION,SITE_STREET_NAME,SITE_UNIT_NUMBER,SITE_MODE,ASSESSMENT_LID,normalized_address,matched_listing_id
372,0400W5ISFQ6YKSRCR1G103,4743 EDGEWOOD RD SW,CEDAR RAPIDS,52404.0,1997-10-09,37000.0,NaN,NaN,NaN,NaN,NaN,NaN,4743 EDGEWOOD RD SW,NaN
679,0405V65DC8K93UVKTF1KIK,432 F AVE NW,CEDAR RAPIDS,52405.0,1997-10-16,8500.0,NaN,NaN,NaN,NaN,NaN,NaN,432 F AVE NW,NaN
856,0406IDJ63PXDH8R42HTBP8,1130 S 12TH ST,MARION,52302.0,1997-10-21,114500.0,NaN,NaN,NaN,NaN,NaN,NaN,1130 S 12TH ST,NaN
935,0404HKRIYEV8RO3BUP9XSC,2389 225TH AVENUE,FORT MADISON,52627.0,2010-09-08,25000.0,NaN,NaN,NaN,NaN,NaN,NaN,2389 225TH AVE,NaN
994,0403Z1SQZUOX2T9D7IXDLY,PRIMROSE AND 118TH AVE,DONNELLSON,52625.0,2010-09-22,28000.0,NaN,NaN,NaN,NaN,NaN,NaN,PRIMROSE AND 118TH AVE,NaN

In [7]:
parcel_x_address = pd.read_csv('data/SF_Professional_IA_20240115/AddressParcelRelation_IA.csv')

In [8]:
parcel_x_address.head()

               parcel_lid             address_lid  fips_code
0  02072P407KL34W1GXQGQAD  0600042MRTVV3D62JDNQZU      19001
1  02067J6TL3NPFE62PYSU4O  060004PR7PXH7KDC015N0W      19001
2  0203ESK7B58JHZ5BZ01D7D  0600073EP02TV2DTH9BWM3      19001
3  0203XLZW2OA084FMJO836N  060007Q90GBHK8KS6HAZQ2      19001
4  0205ZZ44K8NYZN6PXOCX3V  060009LEM6GOOFOB3H4JMP      19001

In [9]:
oms.head()

,DEED_LID,SITE_ADDR,SITE_CITY,SITE_ZIP,DATE_TRANSFER,VAL_TRANSFER,SITE_HOUSE_NUMBER,SITE_DIRECTION,SITE_STREET_NAME,SITE_UNIT_NUMBER,SITE_MODE,ASSESSMENT_LID,normalized_address,matched_listing_id
372,0400W5ISFQ6YKSRCR1G103,4743 EDGEWOOD RD SW,CEDAR RAPIDS,52404.0,1997-10-09,37000.0,NaN,NaN,NaN,NaN,NaN,NaN,4743 EDGEWOOD RD SW,NaN
679,0405V65DC8K93UVKTF1KIK,432 F AVE NW,CEDAR RAPIDS,52405.0,1997-10-16,8500.0,NaN,NaN,NaN,NaN,NaN,NaN,432 F AVE NW,NaN
856,0406IDJ63PXDH8R42HTBP8,1130 S 12TH ST,MARION,52302.0,1997-10-21,114500.0,NaN,NaN,NaN,NaN,NaN,NaN,1130 S 12TH ST,NaN
935,0404HKRIYEV8RO3BUP9XSC,2389 225TH AVENUE,FORT MADISON,52627.0,2010-09-08,25000.0,NaN,NaN,NaN,NaN,NaN,NaN,2389 225TH AVE,NaN
994,0403Z1SQZUOX2T9D7IXDLY,PRIMROSE AND 118TH AVE,DONNELLSON,52625.0,2010-09-22,28000.0,NaN,NaN,NaN,NaN,NaN,NaN,PRIMROSE AND 118TH AVE,NaN

In [10]:
len(oms) - len(oms.dropna(subset='ASSESSMENT_LID'))

3613

In [11]:
unmatched_listings_x_parcels=unmatched_listings.merge(parcel_x_address, how='inner', left_on='add_address_lid', right_on='address_lid')
len(unmatched_listings_x_parcels)

8883

In [12]:
oms.columns

Index(['DEED_LID', 'SITE_ADDR', 'SITE_CITY', 'SITE_ZIP', 'DATE_TRANSFER',
       'VAL_TRANSFER', 'SITE_HOUSE_NUMBER', 'SITE_DIRECTION',
       'SITE_STREET_NAME', 'SITE_UNIT_NUMBER', 'SITE_MODE', 'ASSESSMENT_LID',
       'normalized_address', 'matched_listing_id'],
      dtype='object')

In [13]:
unmatched_listings.columns

Index(['id', 'rebny_id', 'building_id', 'address', 'zip', 'sold_price',
       'last_event', 'add_address_lid', 'add_house_number',
       'add_prefix_direction', 'add_street_name', 'add_suffix_direction',
       'add_suffix_type', 'parcel_lid', 'assessment_lid',
       'land_assessed_value', 'land_market_value', 'match_key',
       'normalized_address', 'check_zip'],
      dtype='object')

In [14]:
unmatched_listings_x_parcels.columns

Index(['id', 'rebny_id', 'building_id', 'address', 'zip', 'sold_price',
       'last_event', 'add_address_lid', 'add_house_number',
       'add_prefix_direction', 'add_street_name', 'add_suffix_direction',
       'add_suffix_type', 'parcel_lid_x', 'assessment_lid',
       'land_assessed_value', 'land_market_value', 'match_key',
       'normalized_address', 'check_zip', 'parcel_lid_y', 'address_lid',
       'fips_code'],
      dtype='object')

In [15]:
parcels_x_assessments = pd.read_csv(f'data/SF_Professional_IA_20240115/ParcelAssessmentRelation_IA.csv')
parcels_x_assessments.head()

   FIPS_CODE          ASSESSMENT_LID              PARCEL_LID
0      19047  0306KG5NXRN56OGAX2M8XI  0207GPOU5IMIRC5HSV8DS5
1      19047  0304AMT1D2FK6S4APXSJXY  0204EK2ME7U0VR7H9FXMFI
2      19047  03047M1PVWNCQVLROE9CAD  0207LPU6AWDE9HRFCOMP9P
3      19047  0306BNJS8EN860J7Q0KUJ6  0204IF65Q4PA4R6QOFUIPI
4      19047  030122BB0FGO86FTUPGFPW  0207II94GENKLVDNQ9GHM6

In [16]:
unmatched_listings_x_assessments = unmatched_listings_x_parcels.merge(parcels_x_assessments, how='inner', left_on='parcel_lid_y', right_on='PARCEL_LID')

In [17]:
unmatched_listings_x_assessments.merge(oms, how='inner', on='ASSESSMENT_LID')[['address', 'zip', 'sold_price', 'last_event', 'normalized_address_y', 'VAL_TRANSFER', 'DATE_TRANSFER']]

,address,zip,sold_price,last_event,normalized_address_y,VAL_TRANSFER,DATE_TRANSFER
0,110 E Linn St,52755,92000,2011-12-05 05:00:00,110 E LINN ST,140296.0,2011-06-30
1,333 W PINE ST,52301,89500,2011-12-20 05:00:00,333 W PNE ST,15000.0,2009-03-19
2,4731 Savannah Ct SE,52403,195000,2011-12-16 05:00:00,4731 SAVANNAH CT SE,440000.0,2023-11-15
3,4731 Savannah Ct SE,52403,195000,2011-12-16 05:00:00,4731 SAVANNAH CT SE,26500.0,2002-09-26
4,4731 Savannah Ct SE,52403,195000,2011-12-16 05:00:00,4731 SAVANNAH CT SE,33500.0,2006-02-03
...,...,...,...,...,...,...,...
27147,2454 Goodwin Drive,52353,245000,2019-08-19 04:00:00,2454 GOODWIN DR,22000.0,2005-06-29
27148,2454 Goodwin Drive,52353,245000,2019-08-19 04:00:00,2454 GOODWIN DR,23500.0,2006-04-10
27149,2454 Goodwin Drive,52353,245000,2019-08-19 04:00:00,2454 GOODWIN DR,175000.0,2006-08-21
27150,47 Vandello Drive,52317,187000,2017-07-13 04:01:00,47 VANDELLO DR,165000.0,2013-01-23
27151,1311 Legend Drive,52340,369000,2023-09-28 04:00:00,1311 LEGEND DR,200000.0,2021-11-24

In [26]:
oms[oms['normalized_address'].str.contains('W PNE ST')].sort_values('DATE_TRANSFER')

,DEED_LID,SITE_ADDR,SITE_CITY,SITE_ZIP,DATE_TRANSFER,VAL_TRANSFER,SITE_HOUSE_NUMBER,SITE_DIRECTION,SITE_STREET_NAME,SITE_UNIT_NUMBER,SITE_MODE,ASSESSMENT_LID,normalized_address,matched_listing_id
1529391,0403GNF8182PW44K88PUCX,398 W PINE ST,MARENGO,52301.0,2005-06-08,9150.0,398.0,W,PINE,NaN,ST,030404VGDFPHLY4EGZZWV2,398 W PNE ST,NaN
1529273,0405C3MNKL6V0B7VZH0VKE,198 W PINE ST,MARENGO,52301.0,2005-09-06,71000.0,198.0,W,PINE,NaN,ST,030303PCLHFYZBWALQ1B2T,198 W PNE ST,NaN
1529418,04040HOZVS3EOKS8NWG1KB,344 W PINE ST,MARENGO,52301.0,2005-12-27,27500.0,344.0,W,PINE,NaN,ST,030233X0KEC8E5MQZCZNSV,344 W PNE ST,NaN
1529321,0403SVKF2AXE5JEFBYZDQN,278 W PINE ST,MARENGO,52301.0,2006-08-21,44500.0,278.0,W,PINE,NaN,ST,03003TYFFGR0QZ86ZXT1I4,278 W PNE ST,NaN
2080472,0403NLUY7NISWH8UDMFUFO,820 W PINE ST,ELDRIDGE,52748.0,2006-09-25,225000.0,820,W,PINE,NaN,ST,0303FVUOJVNP1PUCU5ON2W,820 W PNE ST,NaN
1529291,0404M3ZEFBMHSPOC4U41TH,122 W PINE ST,MARENGO,52301.0,2007-03-15,83000.0,122.0,W,PINE,NaN,ST,0305JBR0PMPHFZDOFEWO78,122 W PNE ST,NaN
1529496,0403SA39UM22W5Y582CG2O,269 W PINE ST,MARENGO,52301.0,2007-07-16,62000.0,269.0,W,PINE,NaN,ST,0304V2ADF9L4SEPC93HDY8,269 W PNE ST,NaN
1533740,04077C9AH5730ZN8UUS015,411 W PINE ST,MARENGO,52301.0,2007-07-26,124500.0,411,W,PINE,NaN,ST,0300SY8N50GYR1UXYU057U,411 W PNE ST,NaN
2078479,0404D2VVVBMJO5DD8O91WY,307 W PINE ST,ELDRIDGE,52748.0,2008-05-14,90000.0,307,W,PINE,NaN,ST,0301WYN255J4340B14UBNF,307 W PNE ST,NaN
1616333,0406FKRAMX75OO4KD4T6DD,110 W PINE ST,WINFIELD,52659.0,2009-01-06,100000.0,110,W,PINE,NaN,ST,0301VQOE10MY775P7Q42X2,110 W PNE ST,NaN
1529444,04052CAVCVAE10GT399CPL,333 W PINE ST,MARENGO,52301.0,2009-03-19,15000.0,333.0,W,PINE,NaN,ST,030473Q64VNZ3IDSBEXV2G,333 W PNE ST,NaN
2080424,0406426ZR1PPRB5RZHSY2Z,815 W PINE ST,ELDRIDGE,52748.0,2009-06-11,255000.0,815,W,PINE,NaN,ST,0300F7LB2L07H9BWLRLBL7,815 W PNE ST,NaN
1617953,0405JNT8PT2VX874ZGBIGT,310 W PINE ST,WINFIELD,52659.0,2009-12-07,80000.0,310.0,W,PINE,NaN,ST,0300IOEDP4VGR38B0RRL6T,310 W PNE ST,NaN
2078578,04024TF7O8YOKUTJF3WPR1,319 W PINE ST,ELDRIDGE,52748.0,2010-12-28,136000.0,319,W,PINE,NaN,ST,0303MOS8F1BWU9FB3KWTVO,319 W PNE ST,NaN
1529292,0404HN8MQTQRTKZZZFQSAG,122 W PINE ST,MARENGO,52301.0,2011-08-18,51000.0,122.0,W,PINE,NaN,ST,0305JBR0PMPHFZDOFEWO78,122 W PNE ST,NaN
1989479,0402Y9IDC629PPOT50RPFK,119 W PINE ST,LONG GROVE,52756.0,2013-03-07,133000.0,119,W,PINE,NaN,ST,03057XMLA91ATY2V98J20S,119 W PNE ST,NaN
1529290,0404MCB8R150LCC11XVLAN,154 W PINE ST,MARENGO,52301.0,2013-08-27,55000.0,154.0,W,PINE,NaN,ST,0306GDZY8L1OLUE74DVQQO,154 W PNE ST,NaN
2078605,0404UZN55N42PV9DP3T909,322 W PINE ST,ELDRIDGE,52748.0,2013-10-17,117500.0,322,W,PINE,NaN,ST,0305PJHXE55XTVKC305ZJF,322 W PNE ST,NaN
2080473,0400T6Q77EX5E41FWHH1UJ,810 W PINE ST,ELDRIDGE,52748.0,2014-04-15,211000.0,810,W,PINE,NaN,ST,0306IM2DG533U8IH1Z38L2,810 W PNE ST,NaN
1683577,0400W9KUPBCS5CJBX3BIQZ,103 W PINE ST,HILLSBORO,52630.0,2014-05-12,68000.0,103.0,W,PINE,NaN,ST,0302SSJFFN3OZ72X4RRBWA,103 W PNE ST,NaN
1529443,040208AUL8917UXFNYKDSK,300 W PINE ST,MARENGO,52301.0,2015-06-01,79500.0,300.0,W,PINE,NaN,ST,0307C21O0N645GLHUT3UI7,300 W PNE ST,NaN
1529495,0404EN2ZVSET5DWGMNB6O9,269 W PINE ST,MARENGO,52301.0,2015-07-20,85000.0,269.0,W,PINE,NaN,ST,0304V2ADF9L4SEPC93HDY8,269 W PNE ST,NaN
1532882,040504CYFVGX4PHXPC3LU2,501 W PINE ST,MARENGO,52301.0,2016-04-11,127000.0,501,W,PINE,NaN,ST,03041G5WTRR8CLYHRNLDT5,501 W PNE ST,NaN
1532883,0404PA4G29UZ6SA5PKIU7H,501 W PINE ST,MARENGO,52301.0,2016-04-29,127000.0,501,W,PINE,NaN,ST,03041G5WTRR8CLYHRNLDT5,501 W PNE ST,NaN
1533741,04038Y8QSAI3RMAOA0SF20,405 W PINE ST,MARENGO,52301.0,2016-05-27,135000.0,405,W,PINE,NaN,ST,03060PKET95YAICCPL6Z6H,405 W PNE ST,NaN
1530677,0405JQR2V11O5JF77PN4Q5,638 W PINE ST,MARENGO,52301.0,2016-08-16,80000.0,638.0,W,PINE,NaN,ST,030273KIHEY53WKG57ZHHC,638 W PNE ST,NaN
1529419,0406VF84ZZUAEJP3WG5480,344 W PINE ST,MARENGO,52301.0,2017-08-07,51000.0,344.0,W,PINE,NaN,ST,030233X0KEC8E5MQZCZNSV,344 W PNE ST,NaN
1529282,0403Y54DKNA2GWNDBZKT6A,154 W PINE ST,MARENGO,52301.0,2017-09-01,69500.0,154.0,W,PINE,NaN,ST,0306GDZY8L1OLUE74DVQQO,154 W PNE ST,NaN
1529403,0400LPYDCY7ITJW46NQ7UI,366 W PINE ST,MARENGO,52301.0,2017-09-27,66000.0,366.0,W,PINE,NaN,ST,03053OY0INPL0X6DI1NHKL,366 W PNE ST,NaN
1530720,04001I6BZS7V4BU9DCR9JW,672 W PINE ST,MARENGO,52301.0,2018-07-02,40000.0,672.0,W,PINE,NaN,ST,0301MIHD6FMAH8DJZEET01,672 W PNE ST,NaN
1615249,04076JVRZQ03718A8FYACB,209 W PINE ST,WINFIELD,52659.0,2018-08-27,76500.0,209,W,PINE,NaN,ST,03011Q8DT94QIFVKXV9V0K,209 W PNE ST,NaN
1529283,04038P1L2J7IA9JOFODCUL,154 W PINE ST,MARENGO,52301.0,2018-09-10,73000.0,154.0,W,PINE,NaN,ST,0306GDZY8L1OLUE74DVQQO,154 W PNE ST,NaN
1529320,040290ZU0UIJSLUQZ09HZM,298 W PINE ST,MARENGO,52301.0,2018-11-02,90000.0,298.0,W,PINE,NaN,ST,0305BICBN0HWXP9BCJ7ELD,298 W PNE ST,NaN
1529284,0403ZCQA22BJ42GP5W4MDF,154 W PINE ST,MARENGO,52301.0,2019-09-13,80000.0,154.0,W,PINE,NaN,ST,0306GDZY8L1OLUE74DVQQO,154 W PNE ST,NaN
2080410,04047NXUJFYJG41X6JTE69,801 W PINE ST,ELDRIDGE,52748.0,2019-10-22,265000.0,801,W,PINE,NaN,ST,0300RM97IGCFDDZYAILRJ8,801 W PNE ST,NaN
1532864,0402611P4C5SXKQRVTR2E8,695 W PINE ST,MARENGO,52301.0,2019-12-31,125000.0,695,W,PINE,NaN,ST,0305X08H1PP9L4FIV4A3IV,695 W PNE ST,NaN
1529544,0407D7IBS7EJO0RWXXQ52X,199 W PINE ST,MARENGO,52301.0,2020-03-02,45000.0,199.0,W,PINE,NaN,ST,03059NFY228WZHLHJSINAV,199 W PNE ST,NaN
1618002,0406ZT5N3O9U39YXF94AE6,310 W PINE ST,WINFIELD,52659.0,2020-06-15,115000.0,310.0,W,PINE,NaN,ST,0300IOEDP4VGR38B0RRL6T,310 W PNE ST,NaN
1532881,0402HTOECVLLTJGOSBLZVL,505 W PINE ST,MARENGO,52301.0,2020-09-23,100000.0,505,W,PINE,NaN,ST,0306PULXCJY68VRHL3CEWY,505 W PNE ST,NaN
1989480,0403GMZWH6AVELHXI4DISX,119 W PINE ST,LONG GROVE,52756.0,2021-04-19,178500.0,119,W,PINE,NaN,ST,03057XMLA91ATY2V98J20S,119 W PNE ST,NaN
1529293,0401N7CARRZGX51ZHVMVNY,122 W PINE ST,MARENGO,52301.0,2021-07-09,88500.0,122.0,W,PINE,NaN,ST,0305JBR0PMPHFZDOFEWO78,122 W PNE ST,NaN
1989452,0404N041WE0U7SNRZWRH5Z,104 W PINE ST,LONG GROVE,52756.0,2022-12-22,333500.0,104,W,PINE,NaN,ST,0304PEUVAEHXWFPZMWVZVR,104 W PNE ST,NaN
1532880,0400J16J5RUBAM5KZNSL0H,605 W PINE ST,MARENGO,52301.0,2023-07-05,196500.0,605,W,PINE,NaN,ST,03063EVZ1ZASRXMKQYDW9M,605 W PNE ST,NaN
2078589,0406U1UY7EO2ZIPEUIRI6B,319 W PINE ST,ELDRIDGE,52748.0,2023-08-24,210000.0,319,W,PINE,NaN,ST,0303MOS8F1BWU9FB3KWTVO,319 W PNE ST,NaN

In [25]:
unmatched_listings[unmatched_listings['normalized_address'].str.contains('W PNE')]

,id,rebny_id,building_id,address,zip,sold_price,last_event,add_address_lid,add_house_number,add_prefix_direction,add_street_name,add_suffix_direction,add_suffix_type,parcel_lid,assessment_lid,land_assessed_value,land_market_value,match_key,normalized_address,check_zip
56,28657132,20113704,15139355.0,333 W PINE ST,52301,89500,2011-12-20 05:00:00,0604634JH5A7DLGSJSZB75,333,W,Pine,NaN,St,0207HH4MBIYD7J6MR4J5RC,030473Q64VNZ3IDSBEXV2G,12700.0,12700.0,333 W PINE ST,333 W PNE ST,52301
34059,28709553,20164767,15157978.0,3804 Yellow Pine Ct NE,52402,157000,2016-09-06 04:00:00,0602ODRU0C0X3FLDTEWA0R,3804,NaN,Yellow Pine,Ne,Ct,0200CSSR860X2H2JL4513F,0304IW2MUKSB8CUUMBUGJA,39800.0,39800.0,3804 YELLOW PINE CT NE,3804 YELLOW PNE CT NE,52402

In [20]:
unmatched_listings.merge(oms, how='inner', left_on=['add_house_number', 'add_prefix_direction', 'add_street_name', 'add_suffix_direction', 'add_suffix_type'],
                         right_on=['SITE_HOUSE_NUMBER','SITE_DIRECTION'])

ValueError: len(right_on) must equal len(left_on)